-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.entrevista
(
    number_participant numeric,
    id_entrevista integer NOT NULL,
    CONSTRAINT entrevista_pkey PRIMARY KEY (id_entrevista)
);

CREATE TABLE IF NOT EXISTS public.entrevistador
(
    id_entrevistador integer NOT NULL,
    nombre text COLLATE pg_catalog."default",
    cedula numeric,
    CONSTRAINT entrevistador_pkey PRIMARY KEY (id_entrevistador)
);

CREATE TABLE IF NOT EXISTS public.opciones
(
    id numeric NOT NULL,
    opciones text[] COLLATE pg_catalog."default",
    CONSTRAINT options_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.preguntas
(
    no_question numeric NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT preguntas_pkey PRIMARY KEY (no_question)
);

CREATE TABLE IF NOT EXISTS public.puntuacion
(
    id numeric NOT NULL,
    scores numeric[],
    CONSTRAINT puntuacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resultados
(
    participant_num integer NOT NULL,
    id_sustancia integer NOT NULL,
    id_entrevista integer NOT NULL,
    number_ques numeric NOT NULL,
    id_entrevistador integer NOT NULL,
    puntuacion integer,
    CONSTRAINT resultados_pkey PRIMARY KEY (id_entrevistador, id_sustancia, participant_num, id_entrevista, number_ques)
);

CREATE TABLE IF NOT EXISTS public.sustancias
(
    id_sustancia integer NOT NULL,
    categoria text COLLATE pg_catalog."default",
    desc_categoria text COLLATE pg_catalog."default",
    CONSTRAINT sustancias_pkey PRIMARY KEY (id_sustancia)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    participant_num integer NOT NULL,
    sexo text,
    edad smallint,
    ocupacion text,
    clinica text,
    barrio text,
    estrato smallint,
    CONSTRAINT usuarios_pkey PRIMARY KEY (participant_num)
);

ALTER TABLE IF EXISTS public.puntuacion
    ADD CONSTRAINT puntuacion_id_fkey FOREIGN KEY (id)
    REFERENCES public.opciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS puntuacion_pkey
    ON public.puntuacion(id);


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_id_entrevista_fkey FOREIGN KEY (id_entrevista)
    REFERENCES public.entrevista (id_entrevista) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_id_entrevistador_fkey FOREIGN KEY (id_entrevistador)
    REFERENCES public.entrevistador (id_entrevistador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_id_sustancia_fkey FOREIGN KEY (id_sustancia)
    REFERENCES public.sustancias (id_sustancia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_participant_num_fkey FOREIGN KEY (participant_num)
    REFERENCES public.usuarios (participant_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_participant_num_fkey1 FOREIGN KEY (participant_num)
    REFERENCES public.usuarios (participant_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;